### ISSUE TITLE
Node issues

### ISSUE THREAD

**Issue by ayarov** [reggev/st-app#12]
- Percentage rounding to XX.XX %
- Make the percentage at the center of the node header
- Move the node name to the node body
- Remove the description
- Make much larger fonts
- Make body size
- Make node fonts and sizes configurable
- Make the node footer much larger (bold?)

**Comment by reggev** [comment]
Can I get a sketch of hot you want it to look? simple boxes with titles is enough

Everything is configurable through the CSS files all the dimensions are relative - not absolute - you cannot set them outside of a CSS file

**Comment by reggev** [comment]
nodes were redesigned on 291b0a350be6745cb531e23570246002d8e238dd
as well as their expand button on a76f4f2d647d541d94c293e636eb7074a905843e
