### ISSUE TITLE
node color is not updated according to updated data

### ISSUE THREAD

**Issue by rdvk** [reggev/st-app#4]
The background color of the text is updated (only the color behind the letters)

**Comment by rdvk** [comment]
st-data is updated.
please pull it and start the json server with "node server.js"

if you provide potential higher than 50, some node params will be updated
for example:
http://localhost:4000/nodes?potential=31
will return the same response

http://localhost:4000/nodes?potential=61
will return the same nodes but "node.properties.nodeRank" and "node.properties.summary.total" will be updated

**Comment by reggev** [comment]
graph component was replaced and is now updating as needed see commit 7080817a6d670c1569bda7eaa4999d3489f5b937
