### ISSUE TITLE
Banner Issues

### ISSUE THREAD

**Issue by ayarov** [reggev/st-app#6]
1. Add a logo (at the top right corner)
2. The banner height is too large
3. Set transparency to 0
4. Make the slider and the searchable filter to half of it's size, and make them fixed size
5. Remove the magnifier icon from the searchable filter (it is a usual drop-down with an option of auto-completion)
6. Remove the approval button when changing the slider value (apply by Enter click)
7. BUG: When setting a slider precise value and hitting Enter, the new values is dropped and restored a previous value
8. Change banner colors to make it more emphasized (contrast)

**Comment by reggev** [comment]
bar was redesigned on f64959c81c74c07977569c2bb9e42741c8196319
