### ISSUE TITLE
Add "Collapse All" button

### ISSUE THREAD

**Issue by ayarov** [reggev/st-app#7]
When clicking this button, all nodes on Org. Tree should be collapse recursively (bring to initial state but preserve the filters).

**Comment by reggev** [comment]
do you mean collapse all the nodes up to the root?
a. you can just collapse the root node
b. why would you need that? what is the use case for this feature?

**Comment by reggev** [comment]
added on daa1618a1f86a7e36c69f93d697315f74a1b0f6a
